#!/bin/sh

# Folders to stow
CONFIG_FOLDERS="bin hypr intellij nvim tmux yazi zsh ghostty wayle"

for folder in $CONFIG_FOLDERS
do
  echo "Stowing folder: $folder"
  stow -t "$HOME" --adopt "$folder"
done
