#!/usr/bin/env zsh
if [[ -z $STOW_FOLDERS ]]; then
    STOW_FOLDERS="intellij,nvim,tmux,zsh,bin,alacritty"
fi

if [[ -z $DOTFILES ]]; then
    DOTFILES=/home/eox/.dotfiles
fi

STOW_FOLDERS=$STOW_FOLDERS DOTFILES=$DOTFILES $DOTFILES/stowScript

